[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
agent_swarm = "56Vy8e8V4E6UZnsa6uDRg8HFiPwroz6nRKh7rm9xAfeK"

[programs.devnet]
agent_swarm = "56Vy8e8V4E6UZnsa6uDRg8HFiPwroz6nRKh7rm9xAfeK"

[programs.mainnet]
agent_swarm = "56Vy8e8V4E6UZnsa6uDRg8HFiPwroz6nRKh7rm9xAfeK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/anchor_tests.ts"
