/**
 * Codama Configuration — Typed Client Generation
 *
 * Codama generates typed TypeScript clients from Anchor IDLs.
 * This replaces hand-rolled instruction builders with fully typed, tree-shakeable clients.
 *
 * Usage:
 *   1. Build the program:  `anchor build`
 *   2. Generate clients:   `npx @codama/cli generate --config codama.config.mjs`
 *
 * The generated client uses @solana/kit types (Address, TransactionMessage, etc.)
 * and integrates natively with the framework-kit patterns.
 *
 * @see https://github.com/codama-idl/codama
 */

import { createFromIdl } from '@codama/nodes-from-anchor'
import { renderJavaScriptVisitor } from '@codama/renderers-js'
import { readFileSync } from 'fs'
import { join } from 'path'

// Load the Anchor IDL (generated by `anchor build`)
const idlPath = join(import.meta.dirname, 'target', 'idl', 'agent_swarm.json')

let codama
try {
  const idl = JSON.parse(readFileSync(idlPath, 'utf-8'))
  codama = createFromIdl(idl)
} catch {
  console.error(
    'IDL not found at target/idl/agent_swarm.json.\n' +
    'Run `anchor build` first to generate the IDL.'
  )
  process.exit(1)
}

// Generate TypeScript client into sdk/typescript/
codama.accept(
  renderJavaScriptVisitor(
    join(import.meta.dirname, 'sdk', 'typescript', 'generated'),
    {
      // Use @solana/kit Address type
      dependencyMap: {
        mplToolbox: '@metaplex-foundation/mpl-toolbox',
      },
    }
  )
)

console.log('Codama client generated at sdk/typescript/generated/')
