/**
 * POST /api/ai-draft
 *
 * Generates a governance proposal draft using an LLM.
 * Supports OpenAI-compatible APIs (OpenAI, Groq, Together, local Ollama).
 *
 * Request body:
 *   { prompt: string, type: ProposalType }
 *
 * Response:
 *   { title: string, description: string, rationale: string }
 *
 * Rate-limited: 10 req/min per IP to protect the API key.
 */

import { NextRequest, NextResponse } from 'next/server'

// ─── Rate limit (simple in-memory, resets on cold start) ──────────────────

const hitMap = new Map<string, { count: number; windowStart: number }>()
const WINDOW_MS  = 60_000
const MAX_PER_WIN = 10

function isRateLimited(ip: string): boolean {
  const now  = Date.now()
  const hit  = hitMap.get(ip)
  if (!hit || now - hit.windowStart > WINDOW_MS) {
    hitMap.set(ip, { count: 1, windowStart: now })
    return false
  }
  if (hit.count >= MAX_PER_WIN) return true
  hit.count++
  return false
}

// ─── Handler ──────────────────────────────────────────────────────────────

export async function POST(req: NextRequest) {
  // Rate limit
  const ip = req.headers.get('x-forwarded-for')?.split(',')[0]?.trim() ?? 'unknown'
  if (isRateLimited(ip)) {
    return NextResponse.json({ error: 'Too many requests. Please wait a moment.' }, { status: 429 })
  }

  // Input validation
  let body: { prompt?: string; type?: string }
  try {
    body = await req.json()
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 })
  }

  const { prompt, type } = body
  if (!prompt || typeof prompt !== 'string' || prompt.length < 5 || prompt.length > 500) {
    return NextResponse.json({ error: 'prompt must be a string between 5 and 500 characters' }, { status: 400 })
  }

  // If no API key configured, return a deterministic placeholder (offline mode)
  const apiKey = process.env.OPENAI_API_KEY ?? process.env.GROQ_API_KEY
  if (!apiKey) {
    return NextResponse.json(buildOfflineDraft(prompt, type ?? 'Trade'))
  }

  const baseUrl = process.env.LLM_BASE_URL ?? 'https://api.openai.com/v1'
  const model   = process.env.LLM_MODEL ?? 'gpt-4o-mini'

  const systemPrompt = `You are a governance advisor for a Solana AI agent swarm called NeuroSwarm.
Your task is to draft clear, concise governance proposals for on-chain execution.
Always respond with valid JSON matching: { "title": string, "description": string, "rationale": string }
Keep title under 80 chars. Description under 300 chars. Rationale under 200 chars.
Proposal type context: ${type ?? 'Trade'}`

  try {
    const llmRes = await fetch(`${baseUrl}/chat/completions`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model,
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user',   content: prompt },
        ],
        max_tokens: 400,
        temperature: 0.6,
        response_format: { type: 'json_object' },
      }),
    })

    if (!llmRes.ok) {
      const errText = await llmRes.text()
      console.error('[ai-draft] LLM API error:', errText)
      // Graceful degradation — don't expose upstream errors to the client
      return NextResponse.json(buildOfflineDraft(prompt, type ?? 'Trade'))
    }

    const llmData = await llmRes.json()
    const content = llmData?.choices?.[0]?.message?.content ?? ''

    let parsed: { title?: string; description?: string; rationale?: string }
    try { parsed = JSON.parse(content) } catch { parsed = {} }

    return NextResponse.json({
      title:       sanitize(parsed.title       ?? 'Governance Proposal'),
      description: sanitize(parsed.description ?? 'Proposal generated by AI assistant.'),
      rationale:   sanitize(parsed.rationale   ?? 'Based on current market conditions.'),
    })
  } catch (err) {
    console.error('[ai-draft] fetch error:', err)
    return NextResponse.json(buildOfflineDraft(prompt, type ?? 'Trade'))
  }
}

// ─── Offline fallback ──────────────────────────────────────────────────────

const TYPE_TEMPLATES: Record<string, { description: string; rationale: string }> = {
  Rebalance: {
    description: 'Rebalance the swarm portfolio to optimal target weights based on current market conditions.',
    rationale:   'Portfolio drift has exceeded threshold; rebalancing reduces risk-adjusted volatility.',
  },
  Trade: {
    description: 'Execute a targeted token swap at the best available price via Jupiter aggregator.',
    rationale:   'Current spread and liquidity conditions support execution at acceptable slippage.',
  },
  'Risk Limit': {
    description: 'Update position size limits and stop-loss parameters for the active trading strategies.',
    rationale:   'Elevated market volatility warrants tighter risk controls to protect capital.',
  },
  Strategy: {
    description: 'Deploy a new automated strategy module with defined entry/exit criteria.',
    rationale:   'Backtested metrics show positive expectancy; live deployment requires governance approval.',
  },
  Emergency: {
    description: 'Emergency protocol: halt all active strategies and move holdings to stable assets.',
    rationale:   'Anomalous market signals detected; preservation of capital takes priority.',
  },
}

function buildOfflineDraft(prompt: string, type: string) {
  const tpl = TYPE_TEMPLATES[type] ?? TYPE_TEMPLATES['Trade']
  const words = prompt.trim().split(/\s+/).slice(0, 8).join(' ')
  return {
    title:       `${type}: ${words}`,
    description: tpl.description,
    rationale:   tpl.rationale,
  }
}

function sanitize(str: string): string {
  return str.replace(/<[^>]*>/g, '').slice(0, 500)
}
